<?php
?>
<span style="font-weight: 400;">This is custom front view.</span>
<!-- alternative this with form and look at interaction -->
<form class="form"  method="post" action="<?php echo $this->getUrl('newmodule/index/result'); ?>">
	<!-- action="<?php // $this->getUrl('newmodule/index/tst') ?>"> -->

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Test Form') ?></span></legend><br>
        <div class="field required">
            <label for="number" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Input') ?></span>
            </label>

            <div class="control">
                <input type="text" id="number"
                       name="number"
                       class="input-text">
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
            </button>
        </div>
    </div>

</form>